export const Components = {
	NONE: '',
	ADD_VARIATION: '+',
	LET_ARITHMETIC_VAR_VAR: 'let a = b + - * / c',
	LET_ARITHMETIC_NUM_NUM: 'let a = 42 + - * / 23',
	LET_ARITHMETIC_VAR_NUM: 'let a = b + - * / 23',
	LET_ARITHMETIC_NUM_VAR: 'let a = 42 + - * / b',
	ARITHMETIC_VAR_VAR: 'a = b + - * / c',
	ARITHMETIC_NUM_NUM: 'a = 42 + - * / 23',
	ARITHMETIC_VAR_NUM: 'a = b + - * / 23',
	ARITHMETIC_NUM_VAR: 'a = 42 + - * / b',
	LET: 'let a = 23',
	VAR_NUM: 'a = 42',
	LET_VAR: 'let a = b',
	VAR_VAR: 'a = b',
	VARIATIONS_SELECTOR: 'Select',
	IF: 'if ( ... ) { ... }',
	END_IF: 'end if',
	ELSE: 'else { ... }',
	END_ELSE: 'end else',
	WHILE: 'while (a >= b) { ... }',
	END_WHILE: 'end while',
	LOG: 'console.log(a)',
} as const;

export type ComponentsKey = typeof Components[keyof typeof Components];
