export enum Step {
	PROGRAM = 'PROGRAM',
	INPUT = 'INPUT',
	REGISTER = 'REGISTER',
	REGISTER_2 = 'REGISTER_2',
	OUTPUT = 'OUTPUT',
	NEXT = 'NEXT',
	PC = 'PC',
	INITIAL = 'INITIAL',
	CLEAR = 'CLEAR',
}
