export const labels: { [index: string]: any } = {
	DE: {
		RAM_HEADER: 'Random Access Machine',
		PROGRAM_HEADER: 'Programm',
		PROGRAM_COUNTER_HEADER: 'PC',
		CPU_HEADER: 'Endliche Kontrolleinheit',
		REGISTER_HEADER: 'Register',
		ACC: 'Akkumulator',
		SAVE_BTN: 'Speichern',
		OPEN_BTN: 'Hochladen',
		LOAD_BTN: 'In RAM laden',
		INPUT_CONTAINER_HEADER: 'Eingabe',
		OUTPUT_CONTAINER_HEADER: 'Ausgabe',
		PAUSE: 'Pause',
		PLAY: 'Play',
		STEP: 'Schritt',
		FASTER: 'Schneller',
		SLOWER: 'Langsamer',
		LOAD_RAM: 'RAM laden',
		CHOOSE: 'Bitte wähle:',
		JS_HEADER: 'JavaScript',
		COMPILE_BTN: 'Kompilieren',
	},
};
